### PR TITLE
Update 20240523

### PR DESCRIPTION
**Pull request by eContento**

### CODE REVIEW

**Comment by gernotstarke** [comment]
Hi David, thanx for your updates to the Jekyll-Thema.

Numerous of your changes are specific to the Madrid-JUG Site (aah - and you closed the PR before I even could comment)...

**Comment by eContento** [comment]
Hi genotstarke,
  I'm afraid it's my fault. I have created the PR against his repository and have dragged David's local changes to yours. I'm sorry

**Comment by gernotstarke** [comment]
no problem. @Per-Starke, the creator of this theme, is my son, and I help him sometimes with his web stuff... therefore I noticed before  he did...

kind regards to Madrid from Cologne! (btw, I love the Spanish Cortado!)

**Comment by dgomezg** [comment]
Actually, this is also a little bit my fault. I forked the initial repo to evaluate it for our first version of the MadridJUG Website. I still have the task of unlinking our current repo with the MadridJUG Website content from your original one, so that we avoid this kind of mistakes again in the future.

I promise to do it this weekend.

Sorry for the inconveniences.

**Comment by dgomezg** [comment]
> no problem. @Per-Starke, the creator of this theme, is my son, and I help him sometimes with his web stuff... therefore I noticed before he did...
> 
> kind regards to Madrid from Cologne! (btw, I love the Spanish Cortado!)

BTW, If you happen to be around Madrid anytime, we owe you some Spanish cortados, just remind us ;)

**Pull request closed without merging**
